# Generated by Django 3.2.8 on 2021-11-08 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Option',
            new_name='Branch',
        ),
    ]
