# Generated by Django 3.2.8 on 2021-11-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor', '0002_rename_option_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
