# Generated by Django 3.2.8 on 2021-11-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor', '0004_college_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(default=50, max_length=254)),
                ('number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
    ]
